config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'articles#index'
  resources :categories, only: [:index, :show]
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_articles, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:index, :show]
  def index
    @articles = Article.all
  end

  def show
    @articles = Article.all.limit(20).order(created_at: :desc)
  end

  def new
    @article = Article.new
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @article = Article.new(article_params)
    @article.category_id = params[:category_id]
    @article.user = current_user
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_articles
    @article = Article.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def article_params
    params.require(:article).permit(:title, :subtitle, :content_1, :content_2, :content_3, :content_4, :photo1, :photo2, :photo3, :footer_1, :footer_2)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_category, only: [:index, :show]
  def index
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def set_category
    @categories = Category.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>


<div class="container">


<%= simple_form_for @article do |f| %>
<%= f.input :title %>
<%= f.input :subtitle %>
<%= f.input :content_1 %>
<%= f.input :content_2 %>
<%= f.input :content_3 %>
<%= f.input :photo1 %>
<%= f.input :photo2 %>
<%= f.input :photo3 %>
<%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<%= render 'shared/navbar' %>
<h3 class="time"><%= Time.now.strftime("%A, %B %d, %Y") %></h3>
<div class="main-articles-wrapper d-block d-md-flex">
  <div class="main-articles">
    <% @articles.last(1).each do |article|  %>
    <%= link_to article_path(article) do %>
    <img src="<%= article.photo1 %> " alt="">
    <h2><%= article.title %></h2>
    <h3><%= article.subtitle %> </h3>
    <% end %>
    <% end %>
  </div>
  <div class="secondary-articles">
    <% @articles.last(3).reverse.drop(1).each do |article| %>
    <img src="<%= article.photo1 %> " alt="">
    <h2><%= article.title %></h2>
    <% end %>
  </div>
</div>
<div class="middle-articles">
  <% @articles.last(11).reverse.drop(3).each do |article|  %>
  <%= link_to article_path(article) do %>
  <div>
    <img src="<%= article.photo1 %> " alt="">
    <h4><%= article.title %></h4>
  </div>
  <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h2>Create an Article</h2>
<div class="container">
  <%= simple_form_for @article do |f| %>
  <div class="row">
    <div class="col">
      <%= f.input :title, input_html: { class: 'form-control' } %>
    </div>
    <div class="col">
      <%= f.input :subtitle, input_html: { class: 'form-control ' } %>
    </div>
  </div>
  <%= f.input :content_1, input_html: { class: 'form-control form-control-lg' } %>
  <%= f.input :content_2, input_html: { class: 'form-control form-control-lg' } %>
  <%= f.input :content_3, input_html: { class: 'form-control form-control-lg' } %>
  <div class="row">
    <div class="col">
      <%= f.input :photo1 %>
    </div>
    <div class="col">
      <%= f.input :footer_1 %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= f.input :photo2 %>
    </div>
    <div class="col">
      <%= f.input :footer_2 %>
    </div>
  </div>
  <%= f.input :photo3 %>
  <p>importante no olvidar poner categoria</p>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Categories") %>
  <br><br>
  <%= f.submit class:"btn btn-primary btn-lg btn-block" %>
  <% end %>
  <br>
</div>
<div class="form-footer mt-5 mb-5 d-flex justify-content-around align-items-center">
  <div>
   <%= link_to "back to index", root_path, class:"btn btn-warning btn-lg btn-block"  %>
 </div>
 <div>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-danger btn-lg btn-block" %>
</div>

</div>

app/views/articles/show.html.erb
<%= render 'shared/navbar' %>
<% if user_signed_in? %>
<%= link_to "edit", edit_article_path(@article)  %>
<%end%>
<div class="article-container">
  <h2><%= @article.category.name %></h2>
  <h1><%= @article.title %></h1>
  <h3><%= @article.subtitle %></h3>
  <img src="<%= @article.photo1 %> " alt="">
  <h4><%= @article.footer_1 %></h4>
  <div class="user-avatar d-flex align-items-center">
    <img src="https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" alt="">
    <h2>By <%= @article.user.email %></h2>
  </div>
  <div class="articles-time ">
    <p><%= @article.created_at.strftime("%b. %d, %Y  Updated %I:%M %P ET")%></p>
  </div>
  <p><%= @article.content_1 %></p>
  <img src="<%= @article.photo2 %> " alt="">
  <h4><%= @article.footer_2 %></h4>
  <p><%= @article.content_2 %></p>
  <img src="<%= @article.photo3 %> " alt="">
  <p><%= @article.content_3 %></p>
</div>

<div class="bottomss d-block d-md-flex">
  <div>
    <h3 class="title">More news</h3>
    <div class="articles-index">
      <% @articles.last(3).each do |article|  %>
      <%= render 'shared/articles_cards', article: article %>
      <% end %>
    </div>
  </div>
  <div class="top-news">
    <h3 class="title">top news</h3>
    <ul class="list-group">
      <% @articles.sample(7).each do |article| %>
      <li class="list-group-item"><%= link_to article.title, article_path(article) %></li>
      <% end %>
    </ul>
    <img src="https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1307&q=80" alt="">
  </div>
</div>

<h3 class="title">Also you can read</h3>
<div class="articles-index-bottom">
  <% @articles.sample(4).each do |article|  %>
  <%= render 'shared/articles_cards', article: article %>
  <% end %>
</div>
<div class="articles-footer">
  <ul class="list-group">
    <li class="list-group-item"><%= image_tag "https://res.cloudinary.com/dw7ox75dg/image/upload/v1559327622/Captura_de_Pantalla_2019-05-31_a_la_s_15.33.10.png" %></li>
    <% @categories.each do |category| %>
    <li class="list-group-item"><%= link_to category.name, category_path(category) %></li>
    <% end %>
  </ul>
</div>

app/views/categories/index.html.erb
<%= render 'shared/navbar' %>
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>
<% @categories.each do |category|  %>
<%= link_to category_path(category) do %>
<%= category.name %>
<% end %>
<% end %>

app/views/categories/show.html.erb
<%= render 'shared/navbar' %>
<div class="article-wrapper">
  <h2 class="cards-title"><%= @category.name %></h2>
  <div class="cards">
    <% @category.articles.last(2).reverse_each do |article| %>
    <%= render 'shared/cards', article: article %>
    <% end %>
  </div>
  <div class="main-cards">
    <% @category.articles.last(10).reverse.drop(2).each do |article|  %>
    <%= render 'shared/cards_2', article: article %>
    <% end %>
  </div>
  <div class="banner-2">
    <img src="https://images.unsplash.com/photo-1541807084-5c52b6b3adef?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" alt="">
  </div>
  <div class="bottom-wrapper">
    <div class="bottom-adds">
      <img src="https://i.pinimg.com/originals/9c/64/33/9c643336b7971d71e959bfa21333828c.png" alt="">
      <img src="https://i.pinimg.com/originals/9c/64/33/9c643336b7971d71e959bfa21333828c.png" alt="">
      <img src="https://i.pinimg.com/originals/9c/64/33/9c643336b7971d71e959bfa21333828c.png" alt="">
    </div>
    <div class="bottom-cards">
      <% @category.articles.reverse_each do |article|  %>
      <%= render 'shared/cards_bottom', article: article %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_articles_cards.html.erb
<div class="articles-cards-index">
  <%= link_to article_path(article) do  %>
  <img src="<%= article.photo1  %>" alt="">
  <h2><%= article.title %></h2>
  <% end %>
</div>

app/views/shared/_cards.html.erb
<div class="card-article">
  <%= link_to article_path(article) do  %>
  <img src="<%= article.photo1  %>" alt="">
  <h2><%= article.title %></h2>
  <h3><%= article.subtitle %></h3>
  <% end %>
</div>

app/views/shared/_cards_2.html.erb
<%= link_to article_path(article) do %>
<div class="cards-2-container">
  <div class="card-2-image">
    <img src="<%= article.photo1 %> " alt="">
  </div>
  <div class="card-2-title">
    <h2><%= article.title %></h2>
    <p><%= article.subtitle %></p>
  </div>

</div>
<% end %>

app/views/shared/_cards_bottom.html.erb
<%= link_to article_path(article) do %>
<div class="cards-bottom-container">
  <div class="card-bottom-title">
    <h2><%= article.title %></h2>
    <p><%= article.subtitle %></p>
  </div>
  <div class="card-bottom-image">
    <img src="<%= article.photo1 %> " alt="">
  </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-login-container">
 <h3 style="font-size: 16px;">
  © 2019 The New York Times Company
 </h3>
 <%= link_to "create article", new_article_path  %>
 <%= link_to "About", root_path %>
 <%= link_to "Help Center", root_path %>
 <%= link_to "Blog", root_path %>
 <%= link_to "Status", root_path %>
 <%= link_to "Jobs", root_path %>
 <%= link_to "Terms", root_path %>
 <%= link_to "Privacy Policy", root_path %>
 <%= link_to "Cookies", root_path %>
 <%= link_to "Ads info", root_path %>
 <%= link_to "Brand", root_path %>
 <%= link_to "Apps", root_path %>
 <%= link_to "Advertise", root_path %>
 <%= link_to "Marketing", root_path %>
 <%= link_to "Businesses", root_path %>
 <%= link_to "Developers", root_path %>
 <%= link_to "Directory", root_path %>
 <%= link_to "Settings", root_path %>

</div>

app/views/shared/_navbar.html.erb
 <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "https://res.cloudinary.com/dw7ox75dg/image/upload/v1559327622/Captura_de_Pantalla_2019-05-31_a_la_s_15.33.10.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

     <% @categories.each do |category| %>
     <li class="nav-item active">
       <%= link_to category_path(category)  do%>

       <%= category.name %>

       <% end %>
     </li>
     <% end %>

   </ul>
 </div>
</div>
<div class="navbar-2">

  <% @categories.each do |category| %>
  <%= link_to category_path(category)  do%>
  <%= category.name %>
  <% end %>
  <% end %>
</div>